version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: fastapi-dev
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fastapi_db
      - DB_FORCE_ROLL_BACK=false
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    working_dir: /workspace

  db:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
